/**********************************************************************************************/
/* FBL_ErrorGroups.h																	 	  */
/*                                                                       					  */
/* Copyright Paradigma, 1998-2017                                        					  */
/* All Rights Reserved.                                                 					  */
/**********************************************************************************************/
//
//
//	! ATTENTION!
//	! This file is automaticaly generated by transform.php
//	! Edit kernel_errors.xml instead of edit this file.
//

#ifndef _FBL_ErrorGroups_h
	#define _FBL_ErrorGroups_h

#include <VShared/FBL/publ/Errors/FBL_Errors.h>

#include <VShared/FBL/publ/Errors/FBL_Exceptions.h>

/**********************************************************************************************/
FBL_Begin_Namespace


/**********************************************************************************************/
// ATTENTION!
// Note, that some exception like xSuccess doesn't need to be thrown.
// Just create and store to the some environment set-of-SQLSTATEs
//


DECLARE_EXCEPTION( xSuccess,                      xException, ERR_OK )
DECLARE_EXCEPTION( xWarning,                      xException, ERR_WARNING )
DECLARE_EXCEPTION( xFeatureError,                 xException, ERR_FEATURE_NOT_SUPPORTED )
DECLARE_EXCEPTION( xConstraintError,              xException, ERR_CONSTRAINT_VIOLATION )
DECLARE_EXCEPTION( xTransactionStateError,        xException, ERR_TRANSACTION_STATE )
DECLARE_EXCEPTION( xInvalidCharSetError,          xException, ERR_INVALID_CHARACTER_SET )
DECLARE_EXCEPTION( xRollbackError,                xException, ERR_ROLLBACK )
DECLARE_EXCEPTION( xDBError,                      xException, ERR_DB_ERROR )
DECLARE_EXCEPTION( xSequenceError,                xException, ERR_SEQUENCE_ERROR )
DECLARE_EXCEPTION( xInsufficientError,            xException, ERR_INSUFFICIENT_RESOURCES )
DECLARE_EXCEPTION( xExternalError,                xException, ERR_EXTERNAL )
DECLARE_EXCEPTION( xInterruptError,               xException, ERR_INTERRUPT_OPERATION )
DECLARE_EXCEPTION( xShutdownError,                xException, ERR_SHUTDOWN )
DECLARE_EXCEPTION( xOSFileError,                  xException, ERR_OS_FILE )
DECLARE_EXCEPTION( xStreamError,                  xException, ERR_STREAM_ERROR )
DECLARE_EXCEPTION( xEncryptionError,              xException, ERR_ENCRYPTION_ERROR )
DECLARE_EXCEPTION( xValueError,                   xException, ERR_VALUE_INVALID )
DECLARE_EXCEPTION( xSSLError,                     xException, ERR_SSL_ERROR )
DECLARE_EXCEPTION( xBonjourError,                 xException, ERR_BONJOUR_ERROR )
DECLARE_EXCEPTION( xPictureError,                 xException, ERR_PICTURE_ERROR )
DECLARE_EXCEPTION( xKeyValueError,                xException, ERR_KEYVALUE_ERROR )
DECLARE_EXCEPTION( xTableError,                   xException, ERR_TABLE_ERROR )
DECLARE_EXCEPTION( xFieldError,                   xException, ERR_FIELD_ERROR )
DECLARE_EXCEPTION( xLinkError,                    xException, ERR_LINK_ERROR )
DECLARE_EXCEPTION( xConnectionError,              xException, ERR_CONNECTION_ERROR )
DECLARE_EXCEPTION( xIndexError,                   xException, ERR_INDEX_ERROR )
DECLARE_EXCEPTION( xIndexStyleError,              xException, ERR_INDEXPREFS_ERROR )
DECLARE_EXCEPTION( xLicenceError,                 xException, ERR_LICENCE_ERROR )
DECLARE_EXCEPTION( xCompressorError,              xException, ERR_COMPRESSOR_ERROR )
DECLARE_EXCEPTION( xXMLParserError,               xException, ERR_XML_PARSER_ERROR )
DECLARE_EXCEPTION( xViewError,                    xException, ERR_VIEW_ERROR )
DECLARE_EXCEPTION( xSetError,                     xException, ERR_SET_ERROR )
DECLARE_EXCEPTION( xMethodError,                  xException, ERR_METHOD_ERROR )
DECLARE_EXCEPTION( xTriggerError,                 xException, ERR_TRIGGER_ERROR )
DECLARE_EXCEPTION( xStoredProcedureError,         xException, ERR_SP_ERROR )
DECLARE_EXCEPTION( xValentinaError,               xException, ERR_VALENTINA_ERROR )
DECLARE_EXCEPTION( xUDFError,                     xException, ERR_UDF_ERROR )
DECLARE_EXCEPTION( xReportError,                  xException, ERR_REPORT_CURSOR_IS_NULL )
DECLARE_EXCEPTION( xTypeError,                    xException, ERR_TYPE_ERROR )
DECLARE_EXCEPTION( xVolumeError,                  xException, ERR_VOLUME_ERROR )
DECLARE_EXCEPTION( xAspectError,                  xException, ERR_ASPECT_ERROR )
DECLARE_EXCEPTION( xInternalError,                xException, ERR_INTERNAL_ERROR )
DECLARE_EXCEPTION( xConfigError,                  xException, ERR_CONFIG_FILE_ERROR )


/**********************************************************************************************/
FBL_End_Namespace

#endif // _FBLErrorGroups_h

